# Generated by Django 4.0.1 on 2022-01-04 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=16)),
                ('mname', models.CharField(blank=True, max_length=16)),
                ('lname', models.CharField(max_length=16)),
                ('legacy', models.CharField(blank=True, max_length=2)),
                ('roll_no', models.IntegerField()),
                ('standard', models.IntegerField()),
                ('section', models.CharField(max_length=1)),
                ('date_of_birth', models.DateField(default='1992-09-25')),
            ],
        ),
    ]
