# Generated by Django 4.0.1 on 2022-01-04 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='legacy',
            field=models.CharField(blank=True, max_length=4),
        ),
    ]
